# Dapr Subscriptions - Event Routing
# Routes events from Kafka topics to application endpoints
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: todo-reminders-sub
spec:
  # Topic to subscribe to
  topic: todo.reminders
  # Route events to this endpoint
  routes:
    default: /events/reminders
  # Pub/Sub component name
  pubsubname: todo-pubsub
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: todo-audit-sub
spec:
  # Topic to subscribe to
  topic: todo.audit
  # Route events to this endpoint
  routes:
    default: /events/audit
  # Pub/Sub component name
  pubsubname: todo-pubsub
