"""Task model - Core data structure for todo items."""

from dataclasses import dataclass


@dataclass
class Task:
    """Represents a todo item with title, description, and completion status.

    Attributes:
        id: Unique identifier for the task (auto-generated by storage layer)
        title: Brief description of the task (required, non-empty)
        description: Detailed description (optional, defaults to empty string)
        completed: Completion status (defaults to False)
    """

    id: int
    title: str
    description: str = ""
    completed: bool = False

    def __post_init__(self) -> None:
        """Validate task fields after initialization."""
        if not self.title or not self.title.strip():
            raise ValueError("Task title cannot be empty")
        self.title = self.title.strip()
        self.description = self.description.strip() if self.description else ""
